layout_spectrum: 1
color:
  saturation: 0.8781362
  brandStrength: 0.202509
  lightness: 0.453405
  brandColors:
    - '#282010'
    - '#FFFFF8'
    - '#B1BFC8'
    - '#B2856D'
    - '#FFC87B'
  rhythmicContrast: 0.5286738
typography_spectrum: 0.109319
name: Hiking Hooligan
